services:
    mariadb:
        build:    requirements/mariadb
        image:    mariadb:1.0
        volumes:
          - db_vol:/var/lib/mysql
        secrets:
          - db_root_password
          - db_password
          - credentials
        env_file: .env
        networks:
          - docker-network
        restart:  on-failure
    wordpress:
        build:    requirements/wordpress
        image:    wordpress:1.0
        volumes:
          - www_vol:/var/www/html
        secrets:
          - db_password
          - credentials
        env_file: .env
        networks:
          - docker-network
        restart:  on-failure
    nginx:
        build:    requirements/nginx
        image:    nginx:1.0
        volumes:
          - www_vol:/var/www/html
        env_file: .env
        networks:
          - docker-network
        ports:
          - "443:443"
        restart:  on-failure

networks:
    docker-network:

secrets:
    credentials:
        file: ../secrets/credentials.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    db_password:
        file: ../secrets/db_password.txt

volumes:
    db_vol:
      driver: local
      driver_opts:
        type:   none
        device: /home/yiken/data/db
        o:      bind
    www_vol:
      driver: local
      driver_opts:
        type:   none
        device: /home/yiken/data/www
        o:      bind
